rheumatic_diseases:
  - rheumatoid arthritis
  - psoriatic arthritis
  - ankylosing spondylitis
  - non-radiographic axial spondyloarthritis
  - giant cell arteritis
  - juvenile idiopathic arthritis
  - systemic lupus erythematosus
  - Anti-neutrophil cytoplasmic autoantibody (ANCA) associated vasculitis 